### ISSUE TITLE
setup.py get "/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'include_package_data'"

### ISSUE THREAD

**Issue by teawater** [tkrajina/srtm.py#34]
But looks it not affect anything.

After:
```
diff --git a/setup.py b/setup.py
index fadf1f1..aeb6c4e 100755
--- a/setup.py
+++ b/setup.py
@@ -15,7 +15,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-import distutils.core as mod_distutilscore
+import setuptools as mod_distutilscore
 
 mod_distutilscore.setup(
     name = 'SRTM.py',
```

There is not any worning.

**Comment by teawater** [comment]
Oops!
This change make it got:
Traceback (most recent call last):
  File "gpxpy02.py", line 4, in <module>
    import srtm
  File "/usr/local/lib/python2.7/dist-packages/srtm/__init__.py", line 17, in <module>
    from . import main as mod_main
  File "/usr/local/lib/python2.7/dist-packages/srtm/main.py", line 21, in <module>
    from . import data      as mod_data
  File "/usr/local/lib/python2.7/dist-packages/srtm/data.py", line 28, in <module>
    import requests as mod_requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 60, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name DependencyWarning

Fixed it with "sudo pip install --upgrade urllib3"
